### ISSUE TITLE
datafiles.cabinet missing in Windows Universal Port 

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#102]
The datafiles.cabinet file is empty in the latest Windows universal Port Build. Can replace with the cabinet file from the master branch to compile and build, but I'm not sure if there are missing items in it.

**Comment by astrojonathan** [comment]
The datafiles.cabinet now has content

**Comment by astrodavid** [comment]
This was never pushed to github on WUP
