### ISSUE TITLE
stereo mode crashes wwt 5.5 

### ISSUE THREAD

**Issue by philrosenfield** [WorldWideTelescope/wwt-windows-client#103]
(Via email)

I'm Rinaldo from Italy.
I downloaded last version of WWT 5.5 version on my pc with Windows 10 installed. It's very nice , but I have a problem. I would like to use 3d stereo functionality in cyan and red mode.
If I select solar system 3d, when activating all stereo modes (except Oculus) WWT immediately crashes
I traied it also using Windows 7 OS but still have problem
In panorama mode, the mars stero images, works fine.

**Comment by patudom** [comment]
See issue #89 .  Jonathan's fixed it for the next build.

**Comment by patudom** [comment]
Oops, and #84
