### ISSUE TITLE
Layer Manager triggers Auto Hide Tabs bug

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#111]
If you hide the left hand layer manager box by clicking the "x" in the upper right hand corner,  "auto hide tabs" stops working, even when a tour is running.  The only way I've found to make the top menu bar hide again is to restart WWT.

(If you click on the "foot" in the lower left corner to make the layer manager menu go away, the autohide feature continues to behave properly.)

**Comment by patudom** [comment]
@pkgw This feels like one that ought to have a straightforward fix.

**Comment by pkgw** [comment]
Thanks for bumping! CC'ing @Carifio24 here again.

**Comment by Carifio24** [comment]
This sounded like it'd be very simple to fix...which turned out to be the case! See #182.

**Comment by pkgw** [comment]
@patudom If you go to [this link](https://dev.azure.com/aasworldwidetelescope/WWT/_build/results?buildId=2294&view=artifacts&pathAsName=false&type=publishedArtifacts), are you able to click through and download files? If so I can point you to how to download an installer and test out the new version. If not we can get you the file another way, if you're interested to test out the fix.
