### ISSUE TITLE
Links to all Spitzer images in WWT are broken

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#112]
The finder scope gives "Image Credits," and Hubble and Chandra images hyperlink to NASA webpages that give more information about the objects.  I think at some point the whole online Spitzer repository was moved to a different url, so all Spitzer images in WWT now have broken links.  Is there any non-back-breaking way to fix this?

**Comment by astrojonathan** [comment]
Spitzer changed all their links. We will have to fix the old WTML files by hand...

**Comment by philrosenfield** [comment]
Closing, duplicate of #30
