### ISSUE TITLE
Adding Minor Planets from MPC tool seems to be broken

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#117]
I am no longer able to add Minor Planets through the "Add Minor Planet from MPC" function, including previously added objects. Perhaps the MPC database changed its directory?

**Comment by astrojonathan** [comment]
We opened an issue with the MPC. They are evidently looking for the browser string on the server and failing with a 500 server error if they don't find it. Since the WWT client does not look like a browser it fails.
This was changed recently, hopefully they can get it working again.
