### ISSUE TITLE
Some Problems about Make Tour

### ISSUE THREAD

**Issue by qu123xxx** [WorldWideTelescope/wwt-windows-client#118]
I'm using WWT to make a complex tour,but I have several problems:

OS Version ：windows 10 pro (build 17134.228)

### 1. The most important is the "Reference Frame" ‘s “Opacity” or "Color Alpha" can not be controlled in "Timeline Editor". 
For example ,if I have Reference A and Reference B under the Sun，then the "3D solar system" interface will  show them in all the tour. But I just want to show A or B in one "Silde" and show the other one in other "Slide" .

### 2.Some colors can't show in the slide. Such as purple, blue, and pink......
This bug was found when I create a silde to show star chart and target it as pink. It became red when 
the slide was created . Color bule will become black and you will see nothing in the windows.

### 6.The model‘s location on Mars can not be fixed by the “Reference Frame”. 
If I don't track the frame, The model will stay there when time goes by，and the ground under it will move away, and the location will change.
If I track the frame model will disappear when time goes by.

**Comment by astrojonathan** [comment]
Can you give me a link to the tour with this issue so I can look into it?

**Comment by qu123xxx** [comment]
Thanks for  your reply.
This is the example and describtion of operation of the tour： 
https://1drv.ms/u/s!AnBkLwQlyfVwlw00bAX5aSvX6Rk1

**Comment by qu123xxx** [comment]
Thanks for your reply.
This is the link of the example : https://1drv.ms/u/s!AnBkLwQlyfVwlw6Kn-TP0wGYQXoN
There are descriptions and the steps of how to repeat the problem in it.

**Comment by philrosenfield** [comment]
Closing. Example links are broken, feel free to reopen or discuss issues [on our forum](https://wwt-forum.org/)

**Comment by philrosenfield** [comment]
Closing. Example links are broken, feel free to reopen or discuss issues [on our forum](https://wwt-forum.org/)
