### ISSUE TITLE
Longitudinal rotation about a reference frame

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#125]
In a tour rotating about a reference frame longitudinally and crossing from a negative longitude value (as seen in the timeline) to a positive longitude value (or vice versa) causes WWT to take the long (usually opposite of desired) way around the object.

The current work around:
Goal to rotate from -150 degrees to 30 (a change of 180 total degrees)
Change final value from 30 to -330, so that the new rotation is from -150 to -330 and this will rotate the desired direction

(per Christina Moraitis)

**Comment by astrodavid** [comment]
Has anything been changed on this...? I can't seem to break it anymore.

**Comment by philrosenfield** [comment]
Can this be closed?
