### ISSUE TITLE
Spherical Mirror Warp Regression 6.0.4.1

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#128]
In version 6.0.4.1, the spherical mirror warps, 16x9 or 4x3, are zoomed in on the usual view which distorts the warp.

**Comment by pkgw** [comment]
Thanks. This is basically just my ignorance, but can you explain to me what you mean when you write that the views are "zoomed in on the usual view"? Thanks.

**Comment by astrodavid** [comment]
Of the three issues I just opened, this is by far the most pressing as I will not be able to use the release in a planetarium mode if this isn't fixed :/ I'll post tomorrow a picture of what it should look like (when I get back to my other computer), but basically we are only viewing perhaps 80% of the usual view, it is cropped on the sides and bottom. All of the Az lines in the image should bend down to the ground.

**Comment by astrodavid** [comment]
No worries! Here is the proper warp from a previous build (5.5.20.1)

![16x9 correct warp grid](https://user-images.githubusercontent.com/18291123/51546464-cb036300-1e29-11e9-8f5a-3f0f447abdab.png)

**Comment by astrodavid** [comment]
Fixed.

**Comment by pkgw** [comment]
Code change, or did the problem not end up being on the WWT side?

**Comment by astrodavid** [comment]
Slight code change: https://github.com/WorldWideTelescope/wwt-windows-client/commit/11a53e1c4f9e4b0f5633cf9a3f94f738ca681df6

**Comment by pkgw** [comment]
Great, thanks — it's helpful to cross-link the issues and the code (exactly like you just did!) for posterity.

**Comment by astrojonathan** [comment]
The issue number is usually included in the PR description, but I missed that.,
