### ISSUE TITLE
Orbit lines are choppy on startup

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#132]
This reverts if another non WWT window is selected or if a tour is loaded...

![choppyorbits2](https://user-images.githubusercontent.com/18291123/51627307-57d01e80-1f07-11e9-86ab-0a24a991caa3.png)

**Comment by pkgw** [comment]
As per the comments on #131 — if you resize the window, do things suddenly tighten up? If so, my guess is that this is basically the same as #131 and could be closed as a duplicate.

**Comment by astrodavid** [comment]
Yes, closed as a duplicate of #131.
