### ISSUE TITLE
Don't drop rendering frames

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#14]
From Alyssa Goodman email on 4/20 after conversation at Northwestern University with various OpenWWT constituents.

Clarification from Mark SubbaRao on 6/15:
"When rendering frames if “Wait for all downloads” is checked frames will be dropped.
 
Haven’t tried all formats but for a 4K domemaster render about 10% of frames won’t be rendered."

**Comment by doctorspaceman** [comment]
Fixed.
