### ISSUE TITLE
While loading csv files containing Chinese，layer appears garbled

### ISSUE THREAD

**Issue by qu123xxx** [WorldWideTelescope/wwt-windows-client#140]
When I load a csv file in below ,WWT apperes garbled.

![image](https://user-images.githubusercontent.com/16397369/61445772-9a3b5b00-a980-11e9-871f-67160ae14b04.png)

![image](https://user-images.githubusercontent.com/16397369/61446009-0fa72b80-a981-11e9-9ac7-7ffd0b57e619.png)

When I copy all the data in the file and paste into wwt. It back to nomal.
![image](https://user-images.githubusercontent.com/16397369/61446225-74fb1c80-a981-11e9-9bd0-4878a0e42459.png)

But I have hunders of files, and I want to use pywwt to create different groups of layers in WindowsClient. Then save it as .wwtl file. Thus I can't  do it manual. But,

1.In pywwt, the `new_layer()` method isn't support 'Geometry' like `TEXT()` or 'Linestring()'.
  The `load()` method happen to the same issue like above.

2.Excel-addin is unavailable.

It's hard  to create about 200 layers manaully:see_no_evil:

**Comment by qu123xxx** [comment]
I find the solution.When I use notepad open the csv file I find the `Linestring` and `TEXT`  is between `"`.
![image](https://user-images.githubusercontent.com/16397369/61455480-37ed5500-a996-11e9-87be-96557a97e582.png)
Delete it and save csv as Unicode or UTF-8 the error would gone.

**Comment by pkgw** [comment]
Thanks for the update — do you think this issue can be closed now?

**Comment by qu123xxx** [comment]
YES，I think it can be closed.
