### ISSUE TITLE
Linux version of the application

### ISSUE THREAD

**Issue by Brensom** [WorldWideTelescope/wwt-windows-client#214]
Why doesn't a program written in C# have a Linux version?
If the program is written in C#, then it should be possible to run it under Mono, but I can't. Why is that?

**Comment by astrojonathan** [comment]
The Web Client is the cross-platform version, and most of the development effort for almost all customers except dedicated planetariums and Kiosk setups is focused on the Web Variants. Linux does not support DirectX/3D, Midi, XBox Controllers, Windowing, and network API's used by the Desktop/Planetarium versions. It is very Windows-specific and performance-tuned for Direct3d. A Linux port would not be justified as there is no budget to either port or maintain such a mammoth port given the tiny market. The beauty of Open Source is if you or an organization wants to try a Linux port you are welcome to take the code and go for it. If someone wants to donate to AAS to fund a Linux port I am sure they would love to entertain the idea, but further development of platform-specific versions is not in the roadmap, and probably won't be.
