### ISSUE TITLE
Spitzer Links to Originating Webpage

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#30]
When investigating an object in the Spitzer collections clicking on the link back to Spitzer web page, the link is broken.  For the example, 

![clipboard01](https://cloud.githubusercontent.com/assets/9676722/10343862/c25a951e-6ce5-11e5-877f-b7eba18f8f7a.jpg)

This points to:
- http://gallery.spitzer.caltech.edu/Imagegallery/image.php?image_name=sig08-008
  This page does still exist at:
- http://www.spitzer.caltech.edu/images/2078-sig08-008-The-Fireworks-Galaxy-NGC-6946-

**Comment by pkgw** [comment]
Fixed in the WWT 2022 data update.
