### ISSUE TITLE
Add new Pluto skin and Ceres skin in SolarSystem view.

### ISSUE THREAD

**Issue by mjbecker0** [WorldWideTelescope/wwt-windows-client#33]

**Comment by doctorspaceman** [comment]
This is the same as issue #81 on wwt-web-client

**Comment by doctorspaceman** [comment]
Sine this is a data issue that affects all clients, I have moved it over as issue number 2 in wwt-home repo.  Closing it here.

**Comment by kfogel** [comment]
Giving full link here: https://github.com/WorldWideTelescope/wwt-home/issues/2
