### ISSUE TITLE
Units for 3D Solar system units do not respect the units popup setting

### ISSUE THREAD

**Issue by AstroRob** [WorldWideTelescope/wwt-windows-client#46]
When adding an orbit reference frame as a solar system layer, the units popup setting is not respected for displaying the orbit lines. It appears the number is always interpreted in meters, regardless of the setting.

**Comment by astrojonathan** [comment]
Yes. I verified this was a bug. The reference frame code is correctly respecting the units, but when it exports the orbital elements structure it does not initialize it with the correct units, I added conversion functions to allow us to normalize the units when the elements are exported to other drawing functions.
I will check this in tonight.

**Comment by astrojonathan** [comment]
Fixed
