### ISSUE TITLE
stopping tour crashes all machines in cluster

### ISSUE THREAD

**Issue by nell-byler** [WorldWideTelescope/wwt-windows-client#48]
When you stop the playback of a tour with version 5.2.9.1 running on cluster, all the machines in the cluster crash.

**Comment by cecilia-donnelly** [comment]
@astrojonathan and @nell-byler, this looks very similar to #47.  Is it the same bug?  (I think maybe you two talked about it and then each of you opened an issue.)

Thanks for the report, Nell, and the quick fix of #47, Jonathan!

**Comment by astrojonathan** [comment]
Fixed. Duplicate of #47.
