### ISSUE TITLE
WWT crashes at the end of playing a tour if "Auto Repeat" -> "All" is checked.

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#51]
Sometimes we auto loop a whole folder's worth of tours at public events, or as an easy way to cache a lot of useful imagery prior to an event if we're not confident that the venue will have a strong internet connection.

In version 5.2.9.1, when we try to do the auto repeat, WWT crashes after playing the first tour, with the error message "WorldWide Telescope has stopped working.  A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available." 

There is a single button in the error window, with the option "Close program."

This isn't a super urgent problem, but it would be nice to see this fixed.  Thanks!

**Comment by astrojonathan** [comment]
Fixed. There was a manhandled null exception when switching tours because for a moment there was a null current tourstop.
