### ISSUE TITLE
Eclipse 2017 USA view broken in latest version of WWT

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#53]
In Curtis's Eclipse 2017 USA tour (filed under Cosmic Events), there is a sequence that showed the Moon eclipsing the Sun, with a view of the corona during totality.
![solar eclipse 2017 tour screen shot 2](https://cloud.githubusercontent.com/assets/12750048/13758151/6083fbf0-e9fe-11e5-871a-69bf06ba0003.PNG)
![2016-03 solar eclipse 2017 tour screen shot](https://cloud.githubusercontent.com/assets/12750048/13758149/5d7cc7fc-e9fe-11e5-87d3-092f09aeaf55.PNG)

This view is now broken in the latest version of WWT (5.2.9.1)

If you just run the tour, it has somehow lost awareness of the location, and the view at the beginning of the sequence is not set up correctly. 

![solar eclipse 2017 tour screen shot 3](https://cloud.githubusercontent.com/assets/12750048/13758202/9d822efa-e9fe-11e5-8f8a-bfeed1c2c183.PNG)

and the Moon does not appear to move across the Sun.  Instead, the two objects are stationary relative to one another, and you don't see the eclipse.  (Notice the Moon is stuck to the lower left of the Sun).
![img_6718](https://cloud.githubusercontent.com/assets/12750048/13758218/b0ed70d0-e9fe-11e5-8245-38662bf7cc36.JPG)

If you go into tour edit mode and click on "show start position" for that slide, it then seems to set up the location correctly, and the view works as it should.  Once that position has been established, the tour works fine on a particular computer.  But if it's never been done, the tour plays in this buggy way.  (If it's been "fixed," on a particular computer, you can unfix it by restoring defaults and clearing the cache).

We use this view in our Moon phases/eclipses lab, and with the 2017 eclipse just over a year away, we need to make sure this is fixed, please!

**Comment by astrojonathan** [comment]
Was fixed
