### ISSUE TITLE
Duplicate slide at end position is using time stamp at beginning of slide, not end

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#54]
When editing a tour in the Solar System view, if you choose "duplicate slide at end camera position" from a slide that has different start and end dates, the new slide is created using the timestamp from the beginning of the slide rather than the end of the slide.

**Comment by astrojonathan** [comment]
Fixed.
The duplicate had been implemented as a copy of the entire slide, then setting the start position to the end, but did not do this for the time.
