### ISSUE TITLE
"Show orbit" settings for individual planets ignored in tour slides.

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#55]
By default, all the planet orbits are shown in the Solar System view.  If you want to turn off the planet orbits and make a new slide with the orbits turned off, the "off" setting is ignored when the tour is run, and the orbits still display even though they are not supposed to.  

If you "show start camera position" from that slide, the orbits appear correctly turned off, and they will stay off as the tour progresses.  But if you run the tour from the beginning, the "orbits off" setting will be ignored again.

I think this is a bug and not a feature?

**Comment by astrojonathan** [comment]
There was a synchronization issue with slide. Fixed
