### ISSUE TITLE
Minor Planet menu should only appear when right clicking on Sun.

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#57]

**Comment by doctorspaceman** [comment]
Minor planets are a reference frame, you can't add reference frames to a layer group. 
In the current implementation Minor planets menu item appears anywhere in the tree with a right click, but can only add minor planets in their orbit around the sun.  

Minor Planet menu should only appear when right clicking on Sun and give an error message when adding a minor planet that already exists.

**Comment by astrojonathan** [comment]
Updated Context Menu to only show Add MPC menu option only for the "Sun" reference frame.
