### ISSUE TITLE
AAS Branding

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#58]
We have to add "American Astronomical Society" before "WorldWide Telescope" replacing what used to be "Microsoft Research WorldWide Telescope".

I've looked through the website, HTML5 web client and Windows desktop client and put all places where this needs to be changed into the specification document (AAS Branding Spec.docx): https://drive.google.com/drive/u/0/folders/0B3UI2GmfMrltVkpzMHJaQU1LNlk.

Note, this issue is replicated in the other (wwt-website, wwt-web-client) repos.

**Comment by astrojonathan** [comment]
Work done.
