### ISSUE TITLE
Cloud Layer uncontrollable in the timeline editor

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#60]
The cloud layer for the earth is able to be placed into the timeline editor in tours, but the opacity remains unchanged in the tour regardless of what it is set at in the timeline.

**Comment by doctorspaceman** [comment]
It looks like this is a new shader for DX11 that didn't implement the fading of the cloud layer.  Probably a big job to fix.

**Comment by astrojonathan** [comment]
Fixed.
