### ISSUE TITLE
New Global Mosaics available

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#61]
The New Horizons team has recently released a new global mosaic for Pluto: http://www.nasa.gov/sites/default/files/thumbnails/image/nh-pmap_cyl_hr_lor_600m.jpg, which should be added into the solar system mode.

Likewise, the Messenger team has released a digital elevation map of Mercury, which should also be included in the solar system mode: http://astrogeology.usgs.gov/search/map/Mercury/Topography/MESSENGER/Mercury_Messenger_USGS_ClrShade_Global_2km.

**Comment by astrodavid** [comment]
67P, Ceres, Vesta, and Charon should also be added, along with a host of moons and dwarf planets.

**Comment by philrosenfield** [comment]
These have been incorporated
