### ISSUE TITLE
Un-needed Right-click Menu items in Layer Manager

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#63]
Sky

Remove everything from menu except:
* Save Layers
* Publish layers to community

Sandbox
* When I add a reference frame and then a 3d model into it - weirdness
* Remove from menu
  * Track this frame
  * Show object
  * Add Odata feed as layer
  * Add great circle
  * Add lat/long grid
  * Add WMS layer

Dome
  * Remove right click menu completely

**Comment by astrojonathan** [comment]
Done. I left the Sandbox items as they are needed to get data into the sandbox.
