### ISSUE TITLE
Stereo anaglyph red cyan setting crashes WWT

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#89]
In the latest version of WWT (5.5.03), if you try to turn on the view setting for anaglyph red cyan stereo, WWT will crash.  (An error message appears and WWT shuts down).  This feature is very important for outreach work, and the WWTA team has several events coming up in April where we would like to show 3D views.

**Comment by astrojonathan** [comment]
This is fixed in the repository, but we need to get a new build out to the website.
