### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by ayyucedemirbas** [WorldWideTelescope/wwt-windows-client#90]
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - WorldWide Telescope, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\Setup1\Setup1.vdproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - WWTExplorer, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\WWTExplorer3d\WWTExplorer.csproj"
	 - MakeDataCabinetFile, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\MakeDataCabinetFile\MakeDataCabinetFile.csproj"
	 - WWTCore, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\WWTCore\WWTCore\WWTCore.csproj"
	 - Solution Items, "Solution Items"
	 - .nuget, ".nuget"
	 - OculusWrap, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\OculusWrap\OculusWrap.csproj"
	 - WWTExplorer, "C:\Users\ay-_-\Desktop\wwt-windows-client-master\wwt-windows-client-master\WWTExplorer.sln"

  I use Visual Studio 2015 and Visual Studio 2017.

**Comment by astrojonathan** [comment]
You need to follow the instructions and install the Visual Studio Setup Components.
[https://github.com/WorldWideTelescope/wwt-windows-client/blob/master/INSTALL.md].

Excerpt from the install.md file... 
To build the installer, you will also need the Visual Studio 2015 Installer Projects add-in found here: [https://visualstudiogallery.msdn.microsoft.com/f1cc3f3e-c300-40a7-8797-c509fb8933b9]
