### ISSUE TITLE
How Do You Turn Off Timeline?

### ISSUE THREAD

**Issue by heywooddogwood** [WorldWideTelescope/wwt-windows-client#94]
The issue:
Once I have added Timeline to a slide, it is impossible to remove from that slide (as far as I know). As a result, whenever you try to change the length of a slide where Timeline has been applied, a dialogue box appears asking how you want to alter the Timeline (regardless of whether there are actually any objects remaining on the Timeline).

How I currently get around this issue:
Respond to the dialogue box and move on.

**Comment by astrojonathan** [comment]
Currently there is no way to remove the time line. You can copy objects from the slide and create a new slide with no timeline and paste them into it. Then set begin and end camera positions to sync settings and slide start and end, then delete the old slide.
