### ISSUE TITLE
Colors of Gaussian (et al.) Data Points

### ISSUE THREAD

**Issue by heywooddogwood** [WorldWideTelescope/wwt-windows-client#95]
The Issue:
When I add a Gaussian marker for a data point/set to the surface of the Earth, I can then right-click on the layer to change the color. However, only 5-10 color options from the honeycomb grid seem to stick. Otherwise the markers revert to transparency and you can no longer visualize the data set (at least, until you find a color that does work).

How I currently get around the issue:
Memorize which colors from the honeycomb work and avoid the others.

**Comment by astrojonathan** [comment]
There are two colors involved. The layer color is multiplied by the item color to get a final color. The layer color that effects the entire data set (leave this white if you want to use independent color per data item) and then item by item color based on data set. This can be using a color map, or thru specific colors being requested. 

If you chose red for the specific item color, then blue for the layer color, then you multiply each component and your net color is black. So if want to have colors be effective for both you must have some red, green and blue in each of the colors, or the results will always be black.
