### ISSUE TITLE
Ability to Control Individual Layers' Opacity

### ISSUE THREAD

**Issue by astrodavid** [WorldWideTelescope/wwt-windows-client#97]
It would be of great benefit to be able to control an individual layer's opacity in the timeline. This works for some layers such as cloud cover or text but moon orbits, or layers that are children of planets, do not have individual opacity/alpha control.

**Comment by astrojonathan** [comment]
This actually is reference frames, not layers as is described. There were a couple of layers that were left out of the ability to add to timeline, that was corrected. I added timeline control to reference frames as well now.
